<?php

namespace Ratasxy\RecargasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroRepository extends EntityRepository
{
    public function sumaPendientes($vendedor, $fecha){     
        return $this->getEntityManager()
            ->createQuery('SELECT sum(r.compra) as compra, sum(r.ganacia) as ganancia FROM RatasxyRecargasBundle:Registro r WHERE r.fecha = :fecha AND r.vendedor = :vendedor AND r.estado=0')
            ->setParameters(array('vendedor' => $vendedor, 'fecha' => $fecha))
            ->getSingleResult();
    }
    
    public function sumaCancelados($vendedor, $fecha){     
        return $this->getEntityManager()
            ->createQuery('SELECT sum(r.compra) as compra, sum(r.ganacia) as ganancia FROM RatasxyRecargasBundle:Registro r WHERE r.fecha = :fecha AND r.vendedor = :vendedor AND r.estado=1')
            ->setParameters(array('vendedor' => $vendedor, 'fecha' => $fecha))
            ->getSingleResult();
    }
}