<?php

namespace Ratasxy\RecargasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroRepository extends EntityRepository
{
}